//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPTTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARDATA
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Longitute { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> X_Position { get; set; }
        public Nullable<double> Y_Position { get; set; }
        public Nullable<double> Z_Position { get; set; }
        public Nullable<double> Azimuth { get; set; }
        public Nullable<double> Pitch { get; set; }
        public Nullable<double> Role { get; set; }
        public string Image { get; set; }
        public string CompassPosition { get; set; }
        public string Extra { get; set; }
        public string Comment { get; set; }
    }
}
